repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: uv run python -m unittest
        language: system
        pass_filenames: false
        stages: [pre-push]
